// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct VotingSystemProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for VotingSystemProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = VotingSystemProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        VotingSystemProxyMethods { wrapped_tx: tx }
    }
}

pub struct VotingSystemProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> VotingSystemProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> VotingSystemProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> VotingSystemProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn create_campaign<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<u64>,
        Arg3: ProxyArg<u64>,
        Arg4: ProxyArg<ManagedVec<Env::Api, ManagedAddress<Env::Api>>>,
        Arg5: ProxyArg<ManagedVec<Env::Api, ManagedBuffer<Env::Api>>>,
        Arg6: ProxyArg<bool>,
        Arg7: ProxyArg<bool>,
    >(
        self,
        title: Arg0,
        description: Arg1,
        start_timestamp: Arg2,
        end_timestamp: Arg3,
        eligible_voters: Arg4,
        options: Arg5,
        is_confidential: Arg6,
        is_sponsored: Arg7,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("createCampaign")
            .argument(&title)
            .argument(&description)
            .argument(&start_timestamp)
            .argument(&end_timestamp)
            .argument(&eligible_voters)
            .argument(&options)
            .argument(&is_confidential)
            .argument(&is_sponsored)
            .original_result()
    }

    pub fn vote<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u8>,
    >(
        self,
        campaign_id: Arg0,
        option: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("vote")
            .argument(&campaign_id)
            .argument(&option)
            .original_result()
    }

    pub fn close_campaign<
        Arg0: ProxyArg<u64>,
    >(
        self,
        campaign_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("closeCampaign")
            .argument(&campaign_id)
            .original_result()
    }

    pub fn get_tallied_votes<
        Arg0: ProxyArg<u64>,
    >(
        self,
        campaign_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, u64>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTalliedVotes")
            .argument(&campaign_id)
            .original_result()
    }

    pub fn get_all_campaigns(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, VotingCampaignView<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAllCampaigns")
            .original_result()
    }

    pub fn get_campaign_by_id<
        Arg0: ProxyArg<u64>,
    >(
        self,
        campaign_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, VotingCampaignDetails<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getCampaignById")
            .argument(&campaign_id)
            .original_result()
    }

    pub fn is_voting_active<
        Arg0: ProxyArg<u64>,
    >(
        self,
        campaign_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isCampaignActive")
            .argument(&campaign_id)
            .original_result()
    }
}

#[type_abi]
#[derive(Debug, NestedEncode, NestedDecode, TopEncode, TopDecode, Clone, ManagedVecItem)]
pub struct VotingCampaignView<Api>
where
    Api: ManagedTypeApi,
{
    pub campaign_id: u64,
    pub owner: ManagedAddress<Api>,
    pub title: ManagedBuffer<Api>,
    pub description: ManagedBuffer<Api>,
    pub start_timestamp: u64,
    pub end_timestamp: u64,
    pub votes_num: u64,
    pub eligible_voters: ManagedVec<Api, ManagedAddress<Api>>,
    pub is_tallied: bool,
    pub is_confidential: bool,
    pub is_sponsored: bool,
}

#[type_abi]
#[derive(Debug, NestedEncode, NestedDecode, TopEncode, TopDecode, Clone, ManagedVecItem)]
pub struct VotingCampaignDetails<Api>
where
    Api: ManagedTypeApi,
{
    pub campaign_id: u64,
    pub owner: ManagedAddress<Api>,
    pub title: ManagedBuffer<Api>,
    pub description: ManagedBuffer<Api>,
    pub options: ManagedVec<Api, ManagedBuffer<Api>>,
    pub start_timestamp: u64,
    pub end_timestamp: u64,
    pub votes: ManagedVec<Api, u8>,
    pub eligible_voters: ManagedVec<Api, ManagedAddress<Api>>,
    pub is_tallied: bool,
    pub is_confidential: bool,
    pub is_sponsored: bool,
}
